### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by kennethgomez01** [phipzzz/crowdsec-dyndns-ip-whitelister#1]
while I change the path to where the whitelist is and no error, the file publicIpWhitelist.yaml is empty meaning there is no content,

**Comment by fliprocks** [comment]
@kennethgomez01 what privileges does the user who executes the crontab have or which users crontab is it? Writing to "/etc/crowdsec/parsers/s02-enrich/" usually requires root privileges.

- What is the output when you execute the script directly?
- What means you changed the path?
Please provide further information.

Besides this, my whitelisters are still working. Even a testing system works as expected.

**Comment by kennethgomez01** [comment]
Hi sorry for late reply, it seems I made it work now.

**Comment by kennethgomez01** [comment]
I will close this issue

**Comment by kennethgomez01** [comment]
Thanks
